name: onscreen_keyboard
description: "Onscreen keyboard for Flutter applications"

version: 0.0.1

homepage: https://github.com/albinpk/onscreen_keyboard
repository: https://github.com/albinpk/onscreen_keyboard/tree/main/packages/onscreen_keyboard
issue_tracker: https://github.com/albinpk/onscreen_keyboard/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

topics:
  - keyboard
  - virtual-keyboard
  - onscreen-keyboard
  - flutter-keyboard
  - flutter-onscreen-keyboard
