include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    specify_nonobvious_property_types: ignore

formatter:
  trailing_commas: preserve
