include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    document_ignores: ignore
  exclude:
    - /example

formatter:
  trailing_commas: preserve
