name: deploy

on:
  push:
    tags:
      - "flutter_onscreen_keyboard-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    uses: albinpk/actions/.github/workflows/pub_deploy.yml@8e2d19bf317141b1331079c63a9d57df865e1efe
    secrets: inherit
    with:
      working-directory: packages/flutter_onscreen_keyboard
